// src/pages/signup/index.tsx
import React, { useEffect, useState, FC, useContext } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { CognitoUserAttribute } from 'amazon-cognito-identity-js'
import { getUserPool } from '@/utilities/aws'
import { URL } from '@/common/constants/url'
import Layout from '@/components/Layout'
import Head from '@/components/pages/Head'
import {
  Grid,
  makeStyles,
  Card,
  CardContent,
  CardActions,
  Button,
  CardHeader,
} from '@material-ui/core'
import { Input, Textarea } from '@/components/elements/Input'

import { Formik, Form, Field } from 'formik'
import * as Yup from 'yup'
import { AuthContext } from '@/auth/AuthProvider'

const SignUp: FC = () => {
  const router = useRouter()
  const auth = useContext(AuthContext)

  useEffect(() => {
    if (auth.currentUser) {
      router.push('/')
    }
  }, [])

  const errorMessage = (message) => <p className="error">{message}</p>
  const validationSchema = Yup.object().shape({
    email: Yup.string().required(
      errorMessage('メールアドレスを入力してください。')
    ),
    password: Yup.string().required(
      errorMessage('パスワードを入力してください。')
    ),
  })
  const onSubmit = async (values) => {
    const { email, password } = values
    const attributeList = [
      new CognitoUserAttribute({
        Name: 'email',
        Value: email,
      }),
    ]
    getUserPool().signUp(email, password, attributeList, [], (err, result) => {
      if (err) {
        console.error(err)
        return
      }
      router.push(URL.SIGNUP_VERIFICATION)
    })
  }

  const initialValues = {
    email: '',
    password: '',
  }

  return (
    <Layout>
      <Head title="会員登録" />
      <section>
        <div className="entry-header">
          <h1 className="entry-title">会員登録</h1>
        </div>
        <div className="entry-content">
          <Grid container justifyContent="center" spacing={1}>
            <Grid item md={12}>
              <Card>
                <Formik
                  initialValues={initialValues}
                  validationSchema={validationSchema}
                  onSubmit={onSubmit}
                >
                  {({
                    setFieldValue,
                    dirty,
                    isValid,
                    values,
                    handleChange,
                    handleBlur,
                  }) => {
                    return (
                      <Form>
                        <CardContent>
                          <Grid
                            item
                            container
                            spacing={1}
                            justifyContent="center"
                          >
                            <Grid item xs={12} sm={12} md={12}>
                              <Input
                                label="メールアドレス"
                                name="email"
                                type="text"
                              />
                            </Grid>
                            <Grid item xs={12} sm={12} md={12}>
                              <Input
                                label="パスワード"
                                name="password"
                                type="password"
                              />
                            </Grid>
                          </Grid>
                        </CardContent>
                        <CardActions>
                          <Grid item xs={12} sm={6} md={6}>
                            <Button
                              disabled={!dirty || !isValid}
                              variant="contained"
                              color="primary"
                              type="Submit"
                            >
                              会員登録する
                            </Button>
                          </Grid>
                        </CardActions>
                      </Form>
                    )
                  }}
                </Formik>
                <CardContent>
                  <Grid item container spacing={1}>
                    <Grid item xs={12} sm={6} md={6}>
                      <Link href={URL.LOGIN}>
                        <a>ログインはこちら</a>
                      </Link>
                    </Grid>
                  </Grid>
                </CardContent>
              </Card>
            </Grid>
          </Grid>
        </div>
      </section>
    </Layout>
  )
}

export default SignUp

// src/pages/signup/index.vue
<template>
  <section>
    <div class="entry-header">
      <h1 class="entry-title">会員登録</h1>
    </div>
    <div class="entry-content">
      <div class="bg-white rounded px-8 pt-6 pb-8 mb-4">
        <div class="grid grid-cols-1 md:grid-cols-1">
          <div class="form-control">
            <p>メールアドレス</p>
            <ElementsInputText
              name="email"
              type="text"
              :default-value="emailField.props.value.value"
              :errors="
                emailField.meta.isTouched.value && emailField.meta.error.value
                  ? 'メールアドレスを入力してください。'
                  : ''
              "
              @input="(e) => emailField.props.onInput(e)"
              @blur="(e) => emailField.props.onBlur(e)"
            />
          </div>
          <div class="form-control">
            <p>パスワード</p>
            <ElementsInputText
              name="password"
              type="password"
              :default-value="passwordField.props.value.value"
              :errors="
                passwordField.meta.isTouched.value &&
                passwordField.meta.error.value
                  ? 'パスワードを入力してください。'
                  : ''
              "
              @input="(e) => passwordField.props.onInput(e)"
              @blur="(e) => passwordField.props.onBlur(e)"
            />
          </div>
          <div>
            <ElementsButtonBasic
              label="会員登録する"
              name="Regist"
              @click="onSubmit"
            />
          </div>
          <div class="mt-5">
            <NuxtLink :to="$C.URL.LOGIN"> ログインはこちら </NuxtLink>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script lang="ts" setup>
const useField = (
  initialValue: string,
  validate: (value: string) => boolean = () => false
) => {
  const value = ref(initialValue)
  const isTouched = ref(false)

  const error = computed(() => {
    return !validate(value.value)
  })

  const onInput = (v) => {
    value.value = v
  }

  const onBlur = () => {
    isTouched.value = true
  }

  return {
    props: { value, onInput, onBlur },
    meta: {
      isTouched,
      error,
    },
  }
}

const presenceValidator = (value: string) => {
  return value.length > 0
}

const emailValidator = (value: string) => {
  const re = /^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/
  return re.test(value)
}

const router = useRouter()
const { $C } = useNuxtApp()

// 各フィールドの定義(バリデーションメソッドの詳細は後述する)
const emailField = useField('', emailValidator)
const passwordField = useField('', presenceValidator)

// フォームのエラー判定。各フィールドにエラー情報を元に判定する。
const error = computed(() => {
  return emailField.meta.error.value || passwordField.meta.error.value
})

// submitメソッド。各フィールドの値を使い、サーバーにPOSTリクエストを送信する。
const onSubmit = async () => {
  if (error.value) {
    console.log(error.value)
    return
  }
  router.push($C.URL.SIGNUP_VERIFICATION)
}
</script>
